### ISSUE TITLE
Compressor ratio is inverted

### ISSUE THREAD

**Issue by DrStoune** [music-dsp-collection/chunkware-simple-dynamics#1]
Compressor attenuation ratio is inverted. As long as this code is not documented I assume it should be working as any compressor algorithm should, so if I want a 2:1 ratio I will naturally to set my ratio parameter to 2. By looking more deeply into the code it seems like it is not working as expected :

As we can read in SimpleCompProcess.inl :
`double gr = overdB * ( ratio_ - 1.0 );	// gain reduction (dB)`
`gr = dB2lin( gr );					// convert dB -> linear`

In this case for exemple: if we have an overdB equal to 1 and we want to apply a 1.2:1 attenuation ratio, gr will be 0.2 and after the conversion from dB to linear scale it gives a 1.02 ratio which will amplify the signal instead of attenuating it. That means that if a want a 1.2:1 ratio I have to set my ratio parameter to 0.83 (aka 1/1.2) in order to have the correct attenuation ratio in the process.

Simple fix would be to change the line to `double gr = overdB * ( (1.0 / ratio_) - 1.0 );`

**Comment by bmarkovic** [comment]
I only salvaged these bits of (to best of my knowledge) public domain code from The Wayback Machine as the site they were on was known to me but has become defunct since then. I am not into DSP or audio programming any longer so feel free to fork or send a PR. Thank you.

**Comment by DrStoune** [comment]
Hello,

Thanks for the precision, after digging more into the code I found out that this behavior is intended (SimpleComp.h:65 `double ratio_; // ratio (compression: < 1 ; expansion: > 1)`). So we can close this issue.

**Comment by charlesism** [comment]
Any chance you could add a notice to the ReadMe about the ratio being inverted?

Thanks for hosting this project. I'm guessing the reason it's here is more-or-less as a historical record of MusicDSP, so it makes sense not to alter the code.

I'm guessing many people who download this repo won't figure out why it's "not working." A one-liner about the inverted ratio in the ReadMe would solve that.
